name: update-date
on:
  push:
    branches:
    - main
jobs:
  set-date:
    permissions:
      contents: read, write
    runs-on: ubuntu-latest
    steps:
    - name: Set update date
      run: | 
        date=$(date +%Y-%m-%d)
        path=${{ github.action_path }}/index.html
        sed -i -E 's/(<span id="deploy_date">).*(<\/span>)/\1'"$date"'\2/g' $path
