name: update-date
on:
  push:
    branches:
    - main
jobs:
  set-date:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v5
    
    - name: Set update date
      run: | 
        date=$(date +%Y-%m-%d)
        path=${{ github.action_path }}/index.html
        sed -i -E 's/(<span id="deploy_date">).*(<\/span>)/\1'"$date"'\2/g' $path

    - name: Configure git and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Deploy date"
        git push
